CREATE SCHEMA events;

CREATE TABLE events."data" (
	dim_date_id date NOT NULL,
	user_id varchar(35) NOT NULL,
	user_access_type varchar(15) NULL,
	event_type varchar(35) NULL,
	category varchar(15) NULL,
	"depth" int2 NULL,
	"action" varchar(18) NULL,
	"content" text NULL,
	screen_url text NULL,
	screenurl_params text NULL,
	event_timestamp timestamp NOT NULL,
	arrival_timestamp timestamp NOT NULL,
	bk_session_id varchar(40) NULL,
	bk_funnel_id varchar(40) NULL,
	application_version_code int4 NULL,
	application_version_name varchar(10) NULL,
	client_cognito_id varchar(60) NULL,
	client_id varchar(45) NULL,
	device_locale_code varchar(30) NULL,
	device_locale_country varchar(8) NOT NULL,
	device_locale_language varchar(20) NULL,
	device_make varchar(60) NULL,
	device_model varchar(45) NULL,
	device_platform_name varchar(20) NULL,
	device_platform_version varchar(10) NULL,
	session_id varchar(36) NOT NULL,
	session_start_timestamp timestamp NOT NULL
);


CREATE TABLE events.invalid_data (
 dim_date_id VARCHAR (100),
 user_id VARCHAR (100),
 user_access_type VARCHAR (100),
 event_type VARCHAR (100),
 category VARCHAR (100),
 depth VARCHAR (100),
 action VARCHAR (100),
 content TEXT,
 screen_url TEXT,
 screenurl_params TEXT,
 event_timestamp VARCHAR (100),
 arrival_timestamp VARCHAR (100),
 bk_session_id VARCHAR (100),
 bk_funnel_id VARCHAR (100),
 application_version_code VARCHAR (100),
 application_version_name VARCHAR (100),
 client_cognito_id VARCHAR (100),
 client_id VARCHAR (100),
 device_locale_code VARCHAR (100),
 device_locale_country VARCHAR (100),
 device_locale_language VARCHAR (100),
 device_make VARCHAR (100),
 device_model VARCHAR (100),
 device_platform_name VARCHAR (100),
 device_platform_version VARCHAR (100),
 session_id VARCHAR (100),
 session_start_timestamp VARCHAR (100)
);