version: '3.5'

services:
  etl:
    build:
      context: .
      dockerfile: docker/etl/Dockerfile
    volumes:
      - .:/var/www/etl

  dwh_database:
    image: postgres:11
    restart: always
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DOCKER_PG_DB}
      - POSTGRES_USER=${DOCKER_PG_USER}
      - POSTGRES_PASSWORD=${DOCKER_PG_PWD}
    ports:
      - "${DOCKER_PG_PORT}:5432"
